# Generated by Django 5.1.6 on 2025-02-28 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='키워드')),
                ('main_intent', models.TextField(blank=True, verbose_name='주요 검색 의도')),
                ('info_needed', models.JSONField(default=list, verbose_name='필요 정보')),
                ('pain_points', models.JSONField(default=list, verbose_name='불편/어려움')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '키워드',
                'verbose_name_plural': '키워드 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='소제목')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='순서')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='key_word.keyword', verbose_name='키워드')),
            ],
            options={
                'verbose_name': '소제목',
                'verbose_name_plural': '소제목 목록',
                'ordering': ['order'],
            },
        ),
    ]
