# Generated by Django 5.1.6 on 2025-03-04 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('content', models.TextField(verbose_name='콘텐츠')),
                ('keywords', models.JSONField(blank=True, null=True, verbose_name='키워드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '콘텐츠 히스토리',
                'verbose_name_plural': '콘텐츠 히스토리 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
