# Generated by Django 5.1.6 on 2025-03-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="is_infographic",
            field=models.BooleanField(default=False),
        ),
    ]
