# Generated by Django 5.1.6 on 2025-02-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('key_word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('news', '뉴스'), ('academic', '학술 자료'), ('statistic', '통계 자료'), ('general', '일반 자료')], max_length=20, verbose_name='자료 유형')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('url', models.URLField(verbose_name='URL')),
                ('snippet', models.TextField(blank=True, verbose_name='스니펫')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='작성자/출처')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='발행일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='key_word.keyword', verbose_name='키워드')),
            ],
            options={
                'verbose_name': '연구 자료',
                'verbose_name_plural': '연구 자료 목록',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatisticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='통계값')),
                ('context', models.TextField(verbose_name='맥락')),
                ('pattern_type', models.CharField(blank=True, max_length=50, verbose_name='패턴 유형')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='research.researchsource', verbose_name='출처')),
            ],
            options={
                'verbose_name': '통계 데이터',
                'verbose_name_plural': '통계 데이터 목록',
            },
        ),
    ]
